# Generated by Django 3.2.2 on 2021-05-10 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact_api', '0002_auto_20210509_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='auth.user'),
            preserve_default=False,
        ),
    ]
